# Generated by Django 5.0.1 on 2024-02-11 17:49

import BlogApp.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Blog main image | width= 1000px height= 667px ', upload_to='blog_main_Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), BlogApp.models.Main_Blog_img_diamension])),
                ('post_date', ckeditor.fields.RichTextField()),
                ('post_by', models.CharField(help_text='Name of posted by | max_length = 30', max_length=30)),
                ('blog_title', models.CharField(help_text='Blog title | max_length = 100', max_length=100)),
                ('blog_internal_img1', models.ImageField(help_text='Blog internal image | width= 2000px height= 1335px ', upload_to='blog_internal_Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), BlogApp.models.Blog_internal_img_diamension])),
                ('blog_content1', ckeditor.fields.RichTextField()),
                ('blog_internal_img2', models.ImageField(help_text='Blog internal image | width= 2000px height= 1335px ', upload_to='blog_internal_Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), BlogApp.models.Blog_internal_img_diamension])),
                ('blog_content2', ckeditor.fields.RichTextField()),
                ('comment_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
