# Generated by Django 5.0.1 on 2024-02-11 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_blogpage_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage_blog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
