# Generated by Django 5.0.1 on 2024-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_blogpage_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage_blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
