# Generated by Django 5.0.1 on 2024-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_blogpage_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage_blog',
            name='author_description',
            field=models.CharField(default='null', help_text="Author's description | max_length = 1000", max_length=1000),
        ),
    ]
