# Generated by Django 5.0.1 on 2024-02-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_blogpage_blog_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage_blog',
            name='created_at',
        ),
    ]
