# Generated by Django 5.0.1 on 2024-02-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_remove_blogpage_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage_blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
