# Generated by Django 5.0.1 on 2024-02-12 08:29

import ckeditor.fields
import django.core.validators
import update.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage_dedicated_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='dedicated_team | width= 512px height= 512px ', upload_to='dedicated_team', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), update.models.dedicated_team_diamension])),
                ('trainer_name', models.CharField(help_text='Trainer name | length max = 20', max_length=20)),
                ('trainer_designation', models.CharField(help_text='Trainer designation | length max = 50', max_length=50)),
                ('twitter_link', models.URLField(blank=True, help_text='Trainer twitter/company link', null=True)),
                ('linkedin_link', models.URLField(blank=True, help_text='Trainer linkedin/company link', null=True)),
                ('google_plus_link', models.URLField(blank=True, help_text='Trainer google_plus/company link', null=True)),
                ('instagram_link', models.URLField(blank=True, help_text='Trainer instagram/company link', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage_Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(help_text='About head bg | width= 848.8px height= 600px ', upload_to='aboutpagehead', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Head_About_diamension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage_MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(help_text='Mission image | width= 600px height= 400px ', upload_to='MissionVision', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.MV_About_diamension])),
                ('title1', models.CharField(help_text='Mission title', max_length=20)),
                ('content1', ckeditor.fields.RichTextField()),
                ('img2', models.ImageField(help_text='Vision image | width= 600px height= 400px ', upload_to='MissionVision', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.MV_About_diamension])),
                ('title2', models.CharField(help_text='Vision title', max_length=20)),
                ('content2', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage_Stablish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Stablished side image | width= 479px height= 612px ', upload_to='stablishedsection', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Stablish_About_diamension])),
                ('title', models.CharField(help_text='Stablish detail title | max_length = 100', max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage_WhychooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(help_text='About WhyUs bg | width= 612px height= 408px ', upload_to='aboutpagehead', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.WhyUs_bg_diamension])),
                ('Column_title1', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('subtitle1', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('content1', models.TextField()),
                ('subtitle2', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('content2', models.TextField()),
                ('subtitle3', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('content3', models.TextField()),
                ('Column_title2', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('subtitle4', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('content4', models.TextField()),
                ('subtitle5', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('content5', models.TextField()),
                ('subtitle6', models.CharField(help_text='Column Title | max_length = 50', max_length=50)),
                ('content6', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyPage_corporate_trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='corporate_trainer | width= 800px height= 850px ', upload_to='corporate_trainer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.corporate_trainer_diamension])),
                ('trainer_name', models.CharField(help_text='Trainer name | length max = 20', max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
                ('trainer_designation', models.CharField(help_text='Trainer designation | length max = 50', max_length=50)),
                ('twitter_link', models.URLField(blank=True, help_text='Trainer twitter/company link', null=True)),
                ('linkedin_link', models.URLField(blank=True, help_text='Trainer linkedin/company link', null=True)),
                ('google_plus_link', models.URLField(blank=True, help_text='Trainer google_plus/company link', null=True)),
                ('instagram_link', models.URLField(blank=True, help_text='Trainer instagram/company link', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_AboutNITD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(help_text='About on home bg | width= 2000px height= 1333px ', upload_to='home_about', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.About_bg_diamension])),
                ('img', models.ImageField(help_text='About on home image | width= 1000px height= 563px ', upload_to='home_about', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.About_main_diamension])),
                ('video_url', models.URLField(help_text='Youtube video URL for About on HomePage')),
                ('title', models.CharField(help_text='About on HomePage title | max_length = 20', max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
                ('trainer_count', models.IntegerField(help_text='Enter the number of Trainers')),
                ('students_count', models.IntegerField(help_text='Enter the number of Studentss')),
                ('course_count', models.IntegerField(help_text='Enter the number of Courses offered')),
                ('seminar_count', models.IntegerField(help_text='Enter the number of Seminars Conducted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_CourseHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Course Field Image | width= 1000px height= 750px ', upload_to='courseHome', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Course_Home_diamension])),
                ('trainerName', models.CharField(help_text="Trainer's Name here | max_length = 20 ", max_length=20)),
                ('courseDuration', models.CharField(help_text='Course duration here | max_length = 20 ', max_length=20)),
                ('courseTitle', models.CharField(help_text='Course title here | max_length = 50 ', max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('coursetopic', ckeditor.fields.RichTextField(default='null')),
                ('coursetech', ckeditor.fields.RichTextField(default='null')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(help_text='Gallery on home | width= 1000px height= 750px ', upload_to='gallery_home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Gallery_Home_diamension])),
                ('img2', models.ImageField(help_text='Gallery on home | width= 1000px height= 750px ', upload_to='gallery_home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Gallery_Home_diamension])),
                ('img3', models.ImageField(help_text='Gallery on home | width= 1000px height= 750px ', upload_to='gallery_home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Gallery_Home_diamension])),
                ('img4', models.ImageField(help_text='Gallery on home | width= 1000px height= 750px ', upload_to='gallery_home', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Gallery_Home_diamension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_HeadCard1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Home_head card1 title | max_length = 20', max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_HeadCard2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Home_head card2 title | max_length = 20', max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_HeadCard3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Home_head card3 title | max_length = 30', max_length=30)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_HeadCard4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Home_head card4 title | max_length = 20', max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_KeyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='KeyPoints title | max_length = 20', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('sub_title1', models.CharField(help_text='KeyPoints subtitle1 | max_length = 50', max_length=50)),
                ('content1', ckeditor.fields.RichTextField()),
                ('sub_title2', models.CharField(help_text='KeyPoints subtitle2 | max_length = 50', max_length=50)),
                ('content2', ckeditor.fields.RichTextField()),
                ('sub_title3', models.CharField(help_text='KeyPoints subtitle3 | max_length = 50', max_length=50)),
                ('content3', ckeditor.fields.RichTextField()),
                ('sub_title4', models.CharField(help_text='KeyPoints subtitle4 | max_length = 50', max_length=50)),
                ('content4', ckeditor.fields.RichTextField()),
                ('sub_title5', models.CharField(help_text='KeyPoints subtitle5 | max_length = 50', max_length=50)),
                ('content5', ckeditor.fields.RichTextField()),
                ('sub_title6', models.CharField(help_text='KeyPoints subtitle6 | max_length = 50', max_length=50)),
                ('content6', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(help_text='KeyPoints side image | width= 408px height= 612px ', upload_to='KeyPoints', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.KeyPoints_diamension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_RequestQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Request a Quote title | max_length = 20', max_length=20)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Client Image | width= 800px height= 850px ', upload_to='Client_review', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Client_Review_diamension])),
                ('comment', ckeditor.fields.RichTextField()),
                ('name', models.CharField(help_text='Client Name | max_length = 20', max_length=20)),
                ('position', models.CharField(help_text='Client Position | max_length = 20', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(help_text='max_length = 150', max_length=150)),
                ('description1', models.CharField(help_text='max_length = 150', max_length=150)),
                ('bg_img1', models.ImageField(help_text='Home Slider | width= 2000px height= 1335px ', upload_to='Home_Slider', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Home_Slider_diamension])),
                ('title2', models.CharField(help_text='max_length = 150', max_length=150)),
                ('description2', models.CharField(help_text='max_length = 150', max_length=150)),
                ('bg_img2', models.ImageField(help_text='Home Slider | width= 2000px height= 1335px ', upload_to='Home_Slider', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Home_Slider_diamension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nav1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='NITD Logo | width= 250px height= 80px ', upload_to='Nav_logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), update.models.NITD_Logo_diamension])),
                ('email', models.EmailField(help_text='Enter Email of Company | max_length = 120', max_length=120)),
                ('call_number', models.CharField(help_text='Enter phone_number of Company', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
