# Generated by Django 5.0.1 on 2024-04-13 06:37

import django.core.validators
import update.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_remove_requestquotefm_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_coursehome',
            name='courseDuration',
        ),
        migrations.RemoveField(
            model_name='homepage_coursehome',
            name='coursetech',
        ),
        migrations.RemoveField(
            model_name='homepage_coursehome',
            name='coursetopic',
        ),
        migrations.RemoveField(
            model_name='homepage_coursehome',
            name='trainerName',
        ),
        migrations.AlterField(
            model_name='homepage_coursehome',
            name='img',
            field=models.ImageField(help_text='Course Field Image ', upload_to='courseHome', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), update.models.Course_Home_diamension]),
        ),
    ]
