# Generated by Django 5.0.1 on 2024-04-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_remove_homepage_coursehome_courseduration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_aboutnitd',
            name='course_count',
        ),
        migrations.RemoveField(
            model_name='homepage_aboutnitd',
            name='seminar_count',
        ),
    ]
