# Generated by Django 5.0.1 on 2024-04-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_remove_homepage_aboutnitd_course_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_gallery',
            name='img4',
        ),
    ]
