# Generated by Django 5.0.1 on 2024-04-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_remove_homepage_gallery_img4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultypage_corporate_trainer',
            name='google_plus_link',
        ),
        migrations.RemoveField(
            model_name='facultypage_corporate_trainer',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='facultypage_corporate_trainer',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='facultypage_corporate_trainer',
            name='twitter_link',
        ),
    ]
