# Generated by Django 5.0.1 on 2024-04-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0007_remove_facultypage_corporate_trainer_google_plus_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage_corporate_trainer',
            name='trainer_name',
            field=models.CharField(help_text='Trainer name | length max = 20', max_length=50),
        ),
    ]
