# Generated by Django 5.0.1 on 2024-04-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0008_alter_facultypage_corporate_trainer_trainer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultypage_corporate_trainer',
            name='trainer_designation',
            field=models.CharField(help_text='Trainer designation | length max = 50', max_length=100),
        ),
    ]
